# example yaml file

meta_path: data/image/test_image_captioner.jsonl # path for the meta data, the format is fixed for image and video
base_folder: image_intermediate_results/ # path to save the intermediate results
save_folder: results/image_generator # path to save the generated images
image_key: image # key for the image in the meta data
text_key: text # key for the text in the meta data
video_key: video # key for the video in the meta data

steps:
  - type: ImageGenerator
    name: FLUXGenerator
    config:
      model_path: black-forest-labs/FLUX.1-dev
      height: 1024
      weight: 1024
      guidance_scale: 4.5
      num_inference_steps: 50
      max_sequence_length: 512
      batch_size: 1
      device: cuda
  - type: ImageGenerator
    name: StableDiffusion3Generator
    config:
      model_path: stabilityai/stable-diffusion-3.5-larges
      height: 1024
      weight: 1024
      guidance_scale: 4.5
      num_inference_steps: 50
      max_sequence_length: 512
      batch_size: 1
      device: cuda
  - type: ImageGenerator
    name: ImageAPIGenerator
    config:
      model: openai:dall-e-3
      api_key: api_key
      api_url: api_url
      height: 1024
      width: 1024
      quality: standard
