# example yaml file

save_per_batch: false
meta_image_path: data/image/images.jsonl
image_folder: /mnt/petrelfs/liuzheng/synth_vlm/playground/train
save_folder: results/image/captions
captioners:
  LLaVACaptioner:
    model_path: /mnt/petrelfs/liuzheng/synth_vlm/playground/model/llava-1.5-7b-hf
    trust_remote_code: true
    tensor_parallel_size: 2
    max_model_len: 2048
    max_num_seqs: 128
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    prompt: What is the content of this image?
    repeat_time: 5
    batch_size: 1000
  LLaVANeXTCaptioner:
    model_path: /mnt/petrelfs/liuzheng/cjz/llava-v1.6-mistral-7b-hf
    trust_remote_code: true
    tensor_parallel_size: 2
    max_model_len: 4096
    max_num_seqs: 128
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    prompt: What is the content of this image?
    repeat_time: 5
    batch_size: 1000
  LLaVAOneVisionCaptioner:
    model_path: /mnt/petrelfs/liuzheng/synth_vlm/playground/model/llava-onevision-qwen2-7b-ov-hf
    trust_remote_code: true
    tensor_parallel_size: 4
    max_model_len: 16384
    max_num_seqs: 128
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    prompt: What is the content of this image?
    repeat_time: 5
    batch_size: 1000
  BLIPCaptioner:
    model_path: /mnt/petrelfs/liuzheng/synth_vlm/playground/model/blip2-opt-2.7b
    trust_remote_code: true
    tensor_parallel_size: 4
    max_model_len: 2048
    max_num_seqs: 128
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    prompt: What is the content of this image?
    repeat_time: 5
    batch_size: 1000
  QwenVLCaptioner:
    model_path: /mnt/petrelfs/liuzheng/hub3/models--Qwen--Qwen2-VL-7B-Instruct/snapshots/51c47430f97dd7c74aa1fa6825e68a813478097f
    trust_remote_code: true
    tensor_parallel_size: 4
    max_model_len: 2048
    max_num_seqs: 128
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    prompt: What is the content of this image?
    repeat_time: 5
    batch_size: 1000
  MLLamaCaptioner:
    model_path: /mnt/petrelfs/liuzheng/hub3/models--meta-llama--Llama-3.2-11B-Vision-Instruct/snapshots/075e8feb24b6a50981f6fdc161622f741a8760b1
    trust_remote_code: true
    tensor_parallel_size: 4
    max_model_len: 1024
    max_num_seqs: 128
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    prompt: What is the content of this image?
    repeat_time: 5
    batch_size: 1000
  Phi3VCaptioner:
    model_path: /mnt/petrelfs/liuzheng/synth_vlm/playground/model/Phi-3-vision-128k-instruct
    trust_remote_code: true
    num_crops: 16
    tensor_parallel_size: 4
    max_model_len: 4096
    max_num_seqs: 128
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    prompt: What is the content of this image?
    repeat_time: 5
    batch_size: 1000
    
