# example yaml file

meta_path: data/text/prompts.jsonl
base_folder: text_intermediate_results/
save_folder: results/text_generator
image_key: image # key for the image in the meta data
text_key: prompt # key for the text in the meta data
video_key: video # key for the video in the meta data

steps:
 - type: TextGenerator
   name: APIGenerator # API KEY must be set in the environment variable
   config:
     model_id: "openai:gpt-4o"
     temperature: 0.75
     top_p: 0.95
     max_tokens: 20
     n: 1 # we can only set n = 1 currently (because of output method)
     stream: False
     stop: null
     presence_penalty: 0.0
     frequency_penalty: 0.0
     prompt: "You are a helpful assistant."
  - type: TextGenerator
    name: LocalModelGenerator
    config:
      device: "cuda"
      model_path: "Qwen/Qwen2.5-1.5B-Instruct"
      n: 1
      best_of: null
      presence_penalty: 0
      frequency_penalty: 0
      repetition_penalty: 1
      temperature: 1
      top_p: 1
      top_k: -1
      min_p: 0
      seed: null
      stop: null
      stop_token_ids: null
      ignore_eos: False
      max_tokens: 32
      min_tokens: 0
      logprobs: null
      prompt_logprobs: null
      detokenize: True
      skip_special_tokens: True
      spaces_between_special_tokens: True
      logits_processors: null
      include_stop_str_in_output: False
      truncate_prompt_tokens: null
      logit_bias: null # Dict[int,float]
      allowed_token_ids: null  # List[int]
      download_dir: "ckpr/models/"
      prompt: "You are a helpful assistant"

  
