APIGenerator:
  model_id: "huggingface:openai-community/gpt2"
  datasetname: "text-generation"
  output_dir: "outputs/textbasic"
  output_file_name: "outputs.jsonl"
  # api_key: "your-api-key"
  # for huggingface model, provide your huggingface token here
  temperature: 0.75
  
