# example yaml file


meta_prompt_path: data/prompt/i2v.jsonl
save_folder: results/videos
generators:
  CogVideoXGenerator:
    model_path: "/mnt/petrelfs/liuzheng/pnx/ckpt/THUDM/CogVideoX-5b-I2V"
  # AllegroGenerator:
  #   model_path: "rhymes-ai/Allegro"
  # CogVideoXT2VGenerator:
  #   model_path: "THUDM/CogVideoX-2b"
  # I2VGenXLGenerator:
  #   model_path: "ali-vilab/i2vgen-xl"
  # SVDGenerator:
  #   model_path: "stabilityai/stable-video-diffusion-img2vid-xt"
  # AnimateDiffGenerator:
  #   model_path: "emilianJR/epiCRealism"
  # VideoLDMGenerator:
  #   model_path: "CompVis/stable-diffusion-v1-4"
  # ModelScopeT2VGenerator:
  #   model_path: "damo-vilab/text-to-video-ms-1.7b"

  # AnimateDiffGenerator:
  #   model_path:


  # MochiGenerator:
  #   model_path: "genmo/mochi-1-preview"
  #   height: 480
  #   width: 848
  #   num_frames: 31
  #   num_inference_steps: 64

    
